# Generated by Django 5.0.6 on 2024-07-05 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 14, 8, 35, 911734)),
        ),
        migrations.AlterField(
            model_name='returned',
            name='time_back',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 14, 8, 35, 911344, tzinfo=datetime.timezone.utc)),
        ),
    ]
