# Generated by Django 5.0.6 on 2024-07-06 06:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tga', '0002_alter_order_date_alter_returned_time_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 23, 42, 36, 378864)),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(verbose_name='موجودی محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت تخفیف'),
        ),
        migrations.AlterField(
            model_name='returned',
            name='time_back',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 6, 42, 36, 378864, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(verbose_name='تعداد ستاره')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tga.product')),
            ],
        ),
    ]
