# Generated by Django 5.0.6 on 2024-07-06 07:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tga', '0003_alter_order_date_alter_product_inventory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 0, 44, 56, 349602)),
        ),
        migrations.AlterField(
            model_name='returned',
            name='time_back',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 7, 44, 56, 333991, tzinfo=datetime.timezone.utc)),
        ),
    ]
