# Generated by Django 5.0.6 on 2024-07-06 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tga', '0004_product_user_alter_order_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/banner')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 1, 40, 24, 251679)),
        ),
        migrations.AlterField(
            model_name='returned',
            name='time_back',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 8, 40, 24, 251679, tzinfo=datetime.timezone.utc)),
        ),
    ]
