# Generated by Django 5.0.6 on 2024-07-06 10:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tga', '0005_banner_alter_order_date_alter_returned_time_back'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 3, 5, 31, 938523)),
        ),
        migrations.AlterField(
            model_name='returned',
            name='time_back',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 10, 5, 31, 938523, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='product_sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_sold', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tga.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
